env:
  COMPANY: tiny
  PRODUCT_NAME: UnityLane2
jobs:
  build-apk:
    platform: android
    steps:
      - uses: player-settings
        with:
          company-name: $(COMPANY)_2
          product-name: $(PRODUCT_NAME)
          version: 1.0.1
      - uses: player-settings-android
        with:
          architectures: !architectures
            - "ARMv7"
            - "ARM64"
          keystore: !keystore
            path: $(KEYSTORE_PATH)
            passwd: $(KEYSTORE_PASSWD)
            alias: $(KEYSTORE_ALIAS)
            alias-passwd: $(KEYSTORE_ALIAS_PASSWD)
  